In [1]:
import pandas as pd

In [36]:
dd = pd.read_csv("./Datasets/daraz_dataset.csv")
# print(dd)

# print(dd.head(10))
# print(dd.shape)
# print(dd.columns)v
# print(dd.info())
# print(dd["TotalAmount"].max())
# print(dd["TotalAmount"].min())
# print(dd["TotalAmount"].mean())
# print(dd[["CustomerName","District"]])
# print(dd.iloc[11]) // this returns the 11th row
# print(dd.iloc[0:5]) // this return the data from 0 to 4 index
# print(dd.iloc[:,2]) // this return the second column only
# print(dd.iloc[:,[2,6,7]]) //different columns
# print(dd.iloc[-1]) //lastrow
# print(dd.iloc[0:5,0:3])
# print(dd.loc[:,["CustomerName","District"]])
# print(dd.loc[dd["District"]=="Kathmandu"])
# print(dd.loc[dd["TotalAmount"]>30000])
#Filter Chaining ---> kathmandu district , esewa paymentMethod
# print(dd.loc[(dd["District"]=="Kathmandu") & (dd["PaymentMethod"]=="eSewa")])
# print(dd.loc[(dd["Category"]== "Electronics") & (dd["Rating"]==5)])
print(dd.sort_values("TotalAmount" , ascending=False))

      OrderID   OrderDate     CustomerName  Age  Gender    District  \
375  DZ100376  2026-02-11       Asha Thapa   18    Male   Bhaktapur
271  DZ100272  2026-01-29  Ramesh Adhikari   41    Male     Itahari
132  DZ100133  2026-02-04         Sita Rai   52  Female   Bhaktapur
435  DZ100436  2026-03-20        Nabin Rai   46    Male      Butwal
472  DZ100473  2026-02-22       Sita Karki   42    Male   Kathmandu
..        ...         ...              ...  ...     ...         ...
94   DZ100095  2026-03-02       Roshan Rai   19    Male  Biratnagar
492  DZ100493  2026-05-04     Kiran Sharma   55  Female    Lalitpur
74   DZ100075  2026-03-18  Roshan Shrestha   49    Male      Butwal
195  DZ100196  2026-05-22    Manish Sharma   19  Female     Chitwan
27   DZ100028  2026-02-03     Rohit Basnet   46  Female     Chitwan

        Category            Product  Quantity  UnitPrice  DiscountPercent  \
375        Books           Notebook         5      45982                0
271  Electronics  Bluetooth Speaker         5      46482                5
132       Sports           Football         5      48481               10
435         Home              Chair         5      43252                0
472        Books      Python Basics         5      44649                5
..           ...                ...       ...        ...              ...
94        Sports           Football         2       1273               10
492    Groceries             Coffee         1       2781               20
74         Books           Notebook         3        468               10
195       Sports           Dumbbell         1        733               20
27         Books   Data Science 101         1        532               10

     TotalAmount PaymentMethod  Rating OrderStatus
375    229910.00       IME Pay       5    Returned
271    220789.50       IME Pay       5   Delivered
132    218164.50       IME Pay       4     Shipped
435    216260.00         eSewa       2     Shipped
472    212082.75           COD       1  Processing
..           ...           ...     ...         ...
94       2291.40         eSewa       2    Returned
492      2224.80        Khalti       5   Cancelled
74       1263.60          Card       4   Cancelled
195       586.40           COD       1  Processing
27        478.80         eSewa       1   Delivered

[500 rows x 15 columns]

In [2]:
bdd= pd.read_csv("./Datasets/bad_daraz_dataset.csv")
print(bdd)

    product_id product_name     category  price discount_percent  rating  \
0            1       Laptop  Electronics  75000               10     4.8
1            2        Phone  Electronics    NaN               15     4.6
2            3        Shoes      Fashion   3500               5%     4.2
3            4      T-Shirt      Fashion   1500               20     NaN
4            5        Watch  Accessories   5500               10     4.5
5            6   Headphones  Electronics   4200              NaN     4.1
6            7       Laptop  Electronics  75000               10     4.8
7            9          Bag      Fashion    abc               12     3.9
8            9        Mouse  Electronics   1800                5     4.3
9           10     Keyboard  Electronics   2500                5     4.4
10          11       Bottle         Home    800                0     5.5
11          12        Chair    Furniture  -2500               10     4.0
12          12        Chair    Furniture  -2500               10     4.0

           stock       seller         city      brand gender_target      age  \
0             25      TechHub    Kathmandu       Dell        Unisex       25
1             40  GadgetNepal      Pokhara    Samsung        Unisex       30
2             60   FashionHub      Itahari       Nike          Male       22
3            150        Style   Biratnagar     Adidas        Female   Female
4   Out of Stock        TimeX    Kathmandu      Casio          Male       28
5             75     AudioPro      Pokhara        JBL        Unisex       24
6             25      TechHub    Kathmandu       Dell        Unisex       25
7             45     CarryAll       Dharan  Wildcraft        Female       19
8            NaN      TechHub    Kathmandu   Logitech        Unisex      NaN
9             35     TechHub    Kathmandu    Logitech        Unisex       21
10           100    HomeStore     Janakpur    Generic        Unisex       26
11            -5      FurniCo     Lalitpur       IKEA        Unisex  Unknown
12            -5      FurniCo     Lalitpur       IKEA        Unisex  Unknown

    reviews
0       120
1       210
2        55
3        30
4        80
5        65
6       120
7        18
8        90
9       110
10       12
11       44
12       44

In [4]:
# bdd.isnull().sum()
# bdd.fillna(0)//missing value ma 0 haldincha
bdd["price"]=pd.to_numeric(bdd["price"] ,errors= "coerce")
# bdd
# bdd["price"].fillna(bdd["price"].mean())

In [ ]:
bdd["age"]= pd.to_numeric(bdd["age"], errors= "coerce")
bdd["age"]= bdd["age"].fillna(bdd["age"].median())
bdd

In [ ]:
# bdd.dropna() //deleteall the row having NaN
# bdd.duplicate() //to see the duplicate data
bdd["discount_percent"]=bdd["discount_percent"].str.replace("%" ," " , regex= False)
bdd

In [4]:
# bdd.duplicated().sum() #hamrodatasets ma kati ota duplicate cah 
# bdd[bdd.duplicated()] #returns what is dupliacate data 
bdd.duplicated("product_id")

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9     False
10    False
11    False
12     True
dtype: bool

In [8]:
# bdd.drop_duplicates(inplace=True)//complete duplicated data removed and updated a real data with new data without duplicates
# bdd
bdd.drop_duplicates(subset="product_id",keep="last", inplace=True)
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
11,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [18]:
# bdd["price"]=pd.to_numeric(bdd["price"], errors="coerce")
# bdd
# bdd[bdd["price"]<0]
# bdd[bdd["rating"]>5]
# bdd.loc[bdd["price"]<0,"price"]=0
bdd=bdd[bdd["price"]>0] #kunai paninegative or extra higher boundary vanda bahira ko lagi chai remove garera replace garcha
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
2,3,Shoes,Fashion,3500.0,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500.0,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
8,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12

In [12]:
sd = pd.DataFrame({
    "Salary" : [1000,2000,3000,5000,7000,8000,9000,12000]
})


#Quartile
median = sd["Salary"].quantile(0.50)
Q1 = sd["Salary"].quantile(0.25)
Q3 = sd["Salary"].quantile(0.75)
Q1
Q3

#IQR
iqr = Q3-Q1

lower_bound = Q1 - (1.5 * iqr)
upper_bound = Q3 + (1.5 * iqr)

upper_bound

np.float64(16500.0)